builds:
  - binary: vangen
    goos:
      - linux
      - macos
      - windows
    goarch:
      - amd64

archives:
  - wrap_in_directory: true
    format: tar.gz
    files:
      - LICENSE
    format_overrides:
    - goos: windows
      format: zip
