language: go

go: 1.x

os:
  - linux
  - osx

env:
  - GO111MODULE=on

script:
  - go test -coverprofile=coverage.txt ./...
  - go vet ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
