steps:
- name: 'golang'
  args: ['go', 'build']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/vangen', '-f', 'Dockerfile.vangen', '.']
images:
- 'gcr.io/$PROJECT_ID/vangen'
